apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: TO_BE_REPLACED
          ports:
          - containerPort: 3000
          env: 
          - name: CLUSTER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: CLUSTER