apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: localhost:5000/myapp
          ports:
          - containerPort: 3000